Config:
  Ping-Command: true
  StaffChat-Command: true
  Info-Command: true
  Private-Message-Command: true
  Report-Command: true
  Request-Command: true
  SocialSpy-Command: true
  Broadcast-Command: true
  Staff-Message: true
  Hub-Command: true
  Hub-Server: lobby
  Hub-Aliases: lobby,lby
  Motd-Command: false
  Maintenance-Command: true
  Announcer-Command: true
  Server-Full-Join: true
  Max-Slots: 100
  Announcer-Broadcast: true
  Block-Commands: true
  Announcers-Use: true
Cooldown:
  Report: 15
  Request: 15
Messages:
  MsgHelp:
  - '&cUtilisation : /msg <player> <message>'
  ReplyHelp:
  - '&cUtilisation : /r <message>'
  Player-Offline: '&c%target_name% est hors ligne.'
  DontReply: '&cVous n''avez personne à qui répondre.'
  DontMessageYourself: '&cVous ne pouvez pas vous envoyer un message vous-même !'
  No-Message: '&cS''il vous plais, veuillez entrer un message.'
  To: '&7(Pour &d%target_name%&7) %message%'
  From: '&7(De &d%player_name%&7) %message%'
  Ping: '&fVotre ping est de &7: &d%ping% &fms'
  Ping-Other: '&dLe ping de %target_name% est de &d%target_ping% &fms'
  SocialSpy-Enabed: '&fSocialSpy &aactivé !'
  SocialSpy-Disabled: '&fSocialSpy &cDésactivé !'
  Msg-Filtred: '&c[SOCIALSPY] &f%player_name% &4--> &f%target_name%&7: &f%message%'
  StaffChat-Help:
  - '&cUsage: /staffchat <message>'
  StaffChat-Format: '&f%server% &7| &c%player%&7: &f%msg%'
  StaffChat-Format-Console: '&fALL &7| &cConsole&7: &f%msg%'
  StaffChat-Enabled: '&9Staff Chat &aactivé&7.'
  StaffChat-Disabled: '&9Staff Chat &cdésactivé&7.'
  Report-Help:
  - '&cUsage: /report <player> <reason>'
  Report-Cooldown-Format: '&cVous devez patienter &l%cooldown%s &csecondes pour renvoyer un message au staff'
  Report-Player-Message: '&aVotre reeport à bien été envoyer à tout les menbres du staff sur tout les serveurs'
  Report-Staff-Message:
  - ''
  - '&fÉméteur de l''avertissment de&7: &d%player_name%'
  - '&fPersonne avertie &7: &d%target_name%'
  - '&fRaison &7: &d%reason%'
  - '&fServeur &7: &d%server%'
  Report-Teleport-Message: '&dCliquez pour téléporter la perssone avertie.'
  Report-Hover-Message: '&dCliquez pour vous téléporter sur le serveur de la personne avertie.'
  No-Contais-Reports: '&cLe joueur &4%target_name% &cn''as pas d''avertissements dans la base de avertie.'
  Clear-Reports-Usage:
  - '&cUtilisation : /clearreports <player>'
  Clear-Reports-Message: 'Les avertissements de &d%target_name% &fon bien été suprimés !'
  Get-Reports-Usage:
  - '&cUtilisation : /getreports <player>'
  Generating-Reports-Message: '&fTous les avertissements envers &d%target_name% &font bien été obtenus'
  Request-Help:
  - '&cUtilisation : /request <message>'
  Request-Cooldown-Format: '&cYou have to wait &l%cooldown%s &cseconds to send a message
    back to the staff'
  Request-Player-Message: '&aVotre message a bien été envoyé à tout les menbres du staff connectés sur tout les serveurs'
  Request-Staff-Message:
  - ''
  - '&dÀ besoin d''assistance.'
  - ''
  - '&fJoueur&7 : &d%player_name%'
  - '&fRaison&7 : &d%request%'
  - '&fServeur&7 : &d%server%'
  - ''
  Staff-Join: '&d%player% &7a rejoin le serveur &f%server%.'
  Staff-Quit: '&d%player% &7a quité le serveur &f%server%.'
  Broadcast-Help:
  - '&cUtilisation : /broadcast <message>'
  Broadcast-Prefix: '&7[&4Alertet&7] '
  Info-Format: TEXT
  Info-Web: 'Les informations de &d%target_name% ont bien été générés.'
  Info-Header-Message: '&fInformation de &d%target_name%'
  Info-Help:
  - '&cUtilisation : /info <player>'
  Info-Text:
  - '&7&m                                            '
  - '&fJoueur&7 : &d%target_name%'
  - '&fServeur&7 : &d%target_server%'
  - '&fPing&7 : &d%target_ping%'
  - '&fIP&7 : &d%target_ip%'
  - '&fUUID&7 : &d%target_uuid%'
  - '&fVersion&7 : &d%target_version%'
  - '&fPays&7 : &d%target_country%'
  - '&7&m                                            '
  Announcer-Use: '&cUtilisation : /announcer <serveur ou all> <titre> <sous-titre>'
  Announcer-Broadcast: '&7[&4%prefix%&7] &4%message%'
  Server-Does-not-exist: '&cLe serveur &4%server% &cn''existe pas !'
  Blocked-Commands-Message:
  - '&cLa commande &l%command% &cest totalement bloquée, ce comportement sera reporté aux staff actuellement connectés et sur notre base de donnée'
  Blocked-Commands-Message-Staff:
  - '&d%target_name% &fa tenté d''utiliser la commande interdite : &d%command%'
  Plugin-List: '&fPlugins &7(&d%plugins_amount%&7): &d%plugins_name%'
  Motd:
    Usage:
    - '&cUsage: /setmotd <line> <text>'
    - '&cUsage: /setmotd maintenance <line> <text>'
    Line-1: '&d&lExample Server &f| &7BungeCore'
    Line-2: '&5Plugin created by &d&lNotCacha'
    Set-Motd-Message: '&aLine %line% has been established correctly, it was replaced
      by %newline%'
  Server-Full: '&cThe network is full at the moment, you can try later or buy rank
    in our store to enter when the server is full store.example.com&7.'
Maintenance:
  Enabled: false
  MOTD:
    Line1: '&dYour Minecraft Network &7| &4Maintenance'
    Line2: '&cEdit the config.yml'
  Serverversion: '&cMaintenance'
  Maintenance-Enabled: '&aMaintenance mode has been activated&7.'
  Maintenance-Disabled: '&cThe network is no longer under maintenance&7.'
  Maintenance-On: '&cRight now the network is under maintenance, you can visit our
    twitter for more information @NCachax&7.'
  Kick-Message: '&cThe network is under maintenance, you can get information about
    this maintenance on our twitter @NCachax&7.'
  Set-Motd-Message: '&aLine %line% has been established correctly, it was replaced
    by %newline%'
  Command-Usage: '&cUsage: /setmotd maintenance <line> <text>'
Announcers:
  Delay: 120
  Type: RANDOM
  announcers:
    '1':
    - '&fWelcome &d%player_name%&f, has our server remember that you can follow us
      on our twitter &d@NCachax'
    - '&fRemember that any doubts or questions you have can be asked to the staff
      via teamspeak, or using the &d/request <request> &fcommand.'
    '2':
    - '&fHey, right now you are in the mode of %player_server% remember that you can
      always run &d/hub &fand go to another mode'
    - '&fYour current Ping is &d%player_ping%&f, if you have lag it could be a problem
      of yours or the server'
